// Rehearsal-only generated bytes; never the observed live placeholder's proof.
import sharp from 'sharp';
import { createHash } from 'node:crypto';
import { placeholderStatement } from '../../ops/staging_web_fixture_preflight.mjs';
export async function programmaticPlaceholder({ width = 960, height = 640, background = '#2A588F' } = {}) {
  const bytes = await sharp({ create: { width, height, channels: 4, background } }).webp({ lossless: true }).toBuffer();
  return { bytes, photo: { classification: 'synthetic_programmatic_placeholder', mimeType: 'image/webp',
    sha256: createHash('sha256').update(bytes).digest('hex'), byteSize: bytes.length, width, height,
    rgbHex: '#2A588F', opaque: true, syntheticAi: false, currentProductEvidence: false,
    testOnlyStatement: placeholderStatement } };
}
