"""Synthetic local fixtures only; never creates a live enrollment invitation."""
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import stat
import subprocess
import tempfile
import unittest
import io
from types import SimpleNamespace
from contextlib import redirect_stdout, redirect_stderr
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[2]
SPEC = importlib.util.spec_from_file_location('invitation_ops', ROOT / 'tool/generate_staging_password_invitation.py')
ops = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(ops)


class InvitationGeneratorTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix='sit-synthetic-invitation-')
        self.root = Path(self.temp.name).resolve()
        os.chmod(self.root, 0o700)
        self.request = self.root / 'request.json'
        self.allowlist = self.root / 'allowlist.json'
        self.output = self.root / 'bundle'
        self.facts = {'email': 'synthetic-invite@example.invalid', 'userId': 'synthetic-user-001', 'ttlSeconds': 3600}
        self.write(self.request, self.facts)
        self.write(self.allowlist, {'schema': 'sit-staging-access-allowlist', 'version': 1, 'allowedUserIds': ['synthetic-user-001']})

    def tearDown(self):
        self.temp.cleanup()

    def write(self, path, value):
        path.write_text(json.dumps(value), encoding='utf8')
        os.chmod(path, 0o600)

    def generate(self, **kwargs):
        return ops.generate(self.request, self.allowlist, self.output, test_mode=True,
                            entropy=lambda: bytes(range(32)), clock=lambda: 1800000000, **kwargs)

    def denied(self):
        with self.assertRaises(ops.InvitationError):
            self.generate()
        self.assertFalse(self.output.exists())
        self.assertFalse(any(p.name.startswith('.sit-invitation-') for p in self.root.iterdir()))

    def test_exact_files_permissions_and_backend_digest_compatibility(self):
        result = self.generate()
        self.assertEqual(set(p.name for p in self.output.iterdir()), {'handoff.json', 'server-record.json'})
        handoff = json.loads((self.output / 'handoff.json').read_text())
        config = json.loads((self.output / 'server-record.json').read_text())
        self.assertEqual(set(handoff), {'schema', 'version', 'email', 'token', 'expiresAt'})
        self.assertEqual(set(config), {'schema', 'version', 'tokenDigest', 'emailDigest', 'userId', 'issuedAt', 'expiresAt'})
        self.assertEqual(len(handoff['token']), 43)
        self.assertNotIn(self.facts['email'], json.dumps(config))
        self.assertNotIn(handoff['token'], json.dumps(config))
        self.assertEqual(config['tokenDigest'], hashlib.sha256(handoff['token'].encode()).hexdigest())
        self.assertEqual(config['emailDigest'], hashlib.sha256((config['tokenDigest'] + '\n' + self.facts['email']).encode()).hexdigest())
        for name in ['handoff.json', 'server-record.json']:
            st = (self.output / name).stat()
            self.assertEqual(stat.S_IMODE(st.st_mode), 0o600)
            self.assertEqual(st.st_nlink, 1)
            self.assertEqual(st.st_uid, os.getuid())
            self.assertEqual(result['files'][name]['sha256'], hashlib.sha256((self.output / name).read_bytes()).hexdigest())
        self.assertEqual(stat.S_IMODE(self.output.stat().st_mode), 0o700)
        self.assertNotIn(handoff['token'], json.dumps(result))
        self.assertNotIn(handoff['email'], json.dumps(result))
        self.assertNotIn(config['userId'], json.dumps(result))
        # The Node resolver independently checks Python-generated bytes, email
        # binding, expiry boundary and normal server config parsing.
        script = '''
          import fs from 'node:fs';
          import os from 'node:os';
          import path from 'node:path';
          import {readStagingPasswordEnrollmentConfiguration as read, resolveStagingPasswordEnrollment as resolve} from './backend/src/staging_password_enrollment.js';
          const bundle = process.argv[1];
          const handoff = JSON.parse(fs.readFileSync(bundle + '/handoff.json'));
          const {schema, version, ...record} = JSON.parse(fs.readFileSync(bundle + '/server-record.json'));
          const now = Date.parse(record.issuedAt);
          const root = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), 'sit-invitation-node-'));
          try {
            fs.chmodSync(root, 0o700);
            const registry = path.join(root, 'registry.json');
            const ordered = {emailDigest:record.emailDigest,expiresAt:record.expiresAt,issuedAt:record.issuedAt,tokenDigest:record.tokenDigest,userId:record.userId};
            fs.writeFileSync(registry, JSON.stringify([ordered]) + '\\n', {mode:0o600});
            fs.chmodSync(registry, 0o600);
            const config = read({SIT_STAGING_PASSWORD_ENROLLMENT_ENABLED:'true',SIT_STAGING_PASSWORD_ENROLLMENT_INVITATIONS_FILE:registry,PRIVATE_PILOT_V4_ENABLED:'true'}, {now, stagingAccess:{deploymentEnvironment:'test',enabled:true,valid:true,allowedUserIds:[record.userId]}});
            if(resolve(config,{token:handoff.token,email:handoff.email,now}).userId !== record.userId) process.exit(2);
            for (const changes of [{email:'other@example.invalid'}, {now:Date.parse(record.expiresAt)}, {now:now-1}]) {
              let denied=false; try {resolve(config,{token:handoff.token,email:handoff.email,now,...changes});} catch {denied=true;}
              if(!denied) process.exit(3);
            }
          } finally { fs.rmSync(root, {recursive:true,force:true}); }
        '''
        done = subprocess.run(['node', '--input-type=module', '-e', script, str(self.output)], cwd=ROOT, capture_output=True)
        self.assertEqual(done.returncode, 0)
        self.assertEqual(done.stdout + done.stderr, b'')

    def test_invalid_request_facts_fail_closed(self):
        for change in [{'email': ' Mixed@example.invalid'}, {'email': 'missing-at'}, {'email': 'a\n@b.invalid'}, {'email': 'é@example.invalid'}, {'userId': 'unknown'}, {'userId': '../x'}, {'ttlSeconds': 0}, {'ttlSeconds': -1}, {'ttlSeconds': 86401}, {'ttlSeconds': True}, {'ttlSeconds': 1.5}, {'extra': 'secret'}]:
            with self.subTest(change=change):
                self.write(self.request, dict(self.facts, **change))
                self.denied()

    def test_input_permissions_type_links_and_owner(self):
        for target in [self.request, self.allowlist]:
            for mode in [0o644, 0o400, 0o660, 0o1600]:
                with self.subTest(path=target.name, mode=mode):
                    os.chmod(target, mode)
                    self.denied()
            os.chmod(target, 0o600)
            alias = self.root / 'alias'
            os.link(target, alias)
            self.denied()
            alias.unlink()
            original = target.with_suffix('.original')
            target.rename(original)
            target.symlink_to(original)
            self.denied()
            target.unlink()
            target.mkdir(mode=0o700)
            self.denied()
            target.rmdir()
            os.mkfifo(target, 0o600)
            self.denied()
            target.unlink()
            original.rename(target)
        with patch.object(ops.os, 'getuid', return_value=os.getuid() + 1):
            self.denied()
        real_fstat = os.fstat
        def foreign_file(fd):
            st = real_fstat(fd)
            if stat.S_ISREG(st.st_mode):
                return SimpleNamespace(st_mode=st.st_mode, st_uid=os.getuid() + 1, st_nlink=st.st_nlink)
            return st
        with patch.object(ops.os, 'fstat', side_effect=foreign_file):
            self.denied()

    def test_destination_private_owned_no_symlink_no_overwrite(self):
        os.chmod(self.root, 0o750)
        self.denied()
        os.chmod(self.root, 0o700)
        for kind in ['file', 'directory', 'symlink']:
            with self.subTest(kind=kind):
                if kind == 'file': self.output.write_text('preserve')
                elif kind == 'directory': self.output.mkdir()
                else: self.output.symlink_to(self.request)
                before = self.request.read_bytes()
                with self.assertRaises(ops.InvitationError): self.generate()
                self.assertEqual(self.request.read_bytes(), before)
                if kind == 'directory': self.output.rmdir()
                else: self.output.unlink()
        self.generate()
        before = (self.output / 'handoff.json').read_bytes()
        with self.assertRaises(ops.InvitationError): self.generate()
        self.assertEqual((self.output / 'handoff.json').read_bytes(), before)

    def test_atomic_failure_cleanup_and_no_partial_publication(self):
        for stage in ['after-handoff', 'after-record', 'before-publish']:
            def failpoint(point):
                self.assertFalse(self.output.exists())
                if point == stage: raise RuntimeError('synthetic-secret-must-not-leak')
            with self.subTest(stage=stage):
                with self.assertRaisesRegex(ops.InvitationError, '^invitation_generation_failed$'):
                    self.generate(failpoint=failpoint)
                self.assertFalse(self.output.exists())
                self.assertEqual(set(p.name for p in self.root.iterdir()), {'request.json', 'allowlist.json'})

    def test_exclusive_publish_race_preserves_competing_target(self):
        def failpoint(point):
            if point == 'before-publish': self.output.mkdir(mode=0o700)
        with self.assertRaises(ops.InvitationError): self.generate(failpoint=failpoint)
        self.assertTrue(self.output.is_dir())
        self.assertEqual(list(self.output.iterdir()), [])
        self.assertFalse(any(p.name.startswith('.sit-invitation-') for p in self.root.iterdir()))

    def test_injection_and_clock_entropy_fail_closed(self):
        for extra in [{'entropy': lambda: bytes(32)}, {'clock': lambda: 0}, {'failpoint': lambda _: None}]:
            with self.subTest(extra=list(extra)):
                with self.assertRaises(ops.InvitationError):
                    ops.generate(self.request, self.allowlist, self.output, **extra)
                self.assertFalse(self.output.exists())
        for entropy, clock in [(lambda: b'short', lambda: 1800000000), (lambda: bytes(32), lambda: -1), (lambda: bytes(32), lambda: float('nan')), (lambda: bytes(32), lambda: True)]:
            with self.assertRaises(ops.InvitationError):
                ops.generate(self.request, self.allowlist, self.output, test_mode=True, entropy=entropy, clock=clock)
            self.assertFalse(self.output.exists())

    def test_generation_expiry_and_backward_clock_deny(self):
        self.facts['ttlSeconds'] = 1
        self.write(self.request, self.facts)
        for final in [1800000001, 1799999999]:
            values = iter([1800000000, final])
            with self.assertRaises(ops.InvitationError):
                ops.generate(self.request, self.allowlist, self.output, test_mode=True, entropy=lambda: bytes(32), clock=lambda: next(values))
            self.assertFalse(self.output.exists())
            self.assertFalse(any(p.name.startswith('.sit-invitation-') for p in self.root.iterdir()))

    def test_postwrite_hardlink_symlink_permission_or_content_tampering_denies(self):
        for kind in ['hardlink', 'symlink', 'mode', 'content']:
            alias = self.root / 'alias'
            def tamper(point):
                if point != 'before-publish': return
                stage = next(p for p in self.root.iterdir() if p.name.startswith('.sit-invitation-'))
                target = stage / 'handoff.json'
                if kind == 'hardlink': os.link(target, alias)
                elif kind == 'symlink':
                    target.unlink()
                    target.symlink_to(self.request)
                elif kind == 'mode': os.chmod(target, 0o644)
                else: target.write_text('tampered')
            with self.subTest(kind=kind):
                with self.assertRaises(ops.InvitationError): self.generate(failpoint=tamper)
                self.assertFalse(self.output.exists())
                if alias.exists(): alias.unlink()
                self.assertEqual(set(p.name for p in self.root.iterdir()), {'request.json', 'allowlist.json'})

    def test_parent_symlink_and_duplicate_json_or_allowlist_deny(self):
        linked = self.root / 'linked'
        linked.symlink_to(self.root, target_is_directory=True)
        with self.assertRaises(ops.InvitationError):
            ops.generate(linked / 'request.json', self.allowlist, self.output)
        with self.assertRaises(ops.InvitationError):
            ops.generate(self.request, self.allowlist, linked / 'bundle')
        linked.unlink()
        self.request.write_text('{"email":"synthetic@example.invalid","email":"other@example.invalid"}')
        self.denied()
        self.write(self.request, self.facts)
        self.write(self.allowlist, {'schema': 'sit-staging-access-allowlist', 'version': 1, 'allowedUserIds': ['synthetic-user-001', 'synthetic-user-001']})
        self.denied()

    def test_staging_name_collision_does_not_remove_existing_directory(self):
        existing = self.root / ('.sit-invitation-' + 'c' * 32)
        existing.mkdir(mode=0o700)
        with patch.object(ops.secrets, 'token_hex', return_value='c' * 32):
            with self.assertRaises(ops.InvitationError): self.generate()
        self.assertTrue(existing.is_dir())
        self.assertFalse(self.output.exists())

    def test_cli_success_has_only_status_paths_and_hashes(self):
        # Exercise production entropy only with namespaced local synthetic data;
        # no record is loaded into any server configuration.
        stdout, stderr = io.StringIO(), io.StringIO()
        with redirect_stdout(stdout), redirect_stderr(stderr):
            status = ops.main(['--request-file', str(self.request), '--allowlist-file', str(self.allowlist), '--output-bundle', str(self.output)])
        self.assertEqual(status, 0)
        self.assertEqual(stderr.getvalue(), '')
        result = json.loads(stdout.getvalue())
        self.assertEqual(set(result), {'status', 'path', 'files'})
        handoff = json.loads((self.output / 'handoff.json').read_text())
        for secret in [handoff['token'], self.facts['email'], self.facts['userId']]:
            self.assertNotIn(secret, stdout.getvalue())
        self.assertEqual(result['status'], 'created')

    def test_unsupported_platform_fails_closed_and_cleans(self):
        with patch.object(ops.sys, 'platform', 'unsupported'):
            self.denied()

    def test_ttl_boundary_and_file_sync_failure(self):
        for ttl in [1, 86400]:
            self.facts['ttlSeconds'] = ttl
            self.write(self.request, self.facts)
            target = self.root / ('boundary-' + str(ttl))
            ops.generate(self.request, self.allowlist, target, test_mode=True, entropy=lambda: bytes(32), clock=lambda: 1800000000)
            record = json.loads((target / 'server-record.json').read_text())
            import datetime
            issued = datetime.datetime.fromisoformat(record['issuedAt'].replace('Z', '+00:00'))
            expiry = datetime.datetime.fromisoformat(record['expiresAt'].replace('Z', '+00:00'))
            self.assertEqual((expiry - issued).total_seconds(), ttl)
        with patch.object(ops.os, 'fsync', side_effect=OSError('synthetic-write-failure')):
            with self.assertRaisesRegex(ops.InvitationError, '^invitation_generation_failed$'):
                self.generate()
        self.assertFalse(self.output.exists())
        self.assertFalse(any(p.name.startswith('.sit-invitation-') for p in self.root.iterdir()))

    def test_publish_durability_failure_preserves_complete_bundle_and_signals_uncertainty(self):
        real_sync = ops.os.fsync
        parent_inode = self.root.stat().st_ino
        def sync(fd):
            if os.fstat(fd).st_ino == parent_inode:
                raise OSError('synthetic-sensitive-durability-error')
            real_sync(fd)
        stdout, stderr = io.StringIO(), io.StringIO()
        with patch.object(ops.os, 'fsync', side_effect=sync), redirect_stdout(stdout), redirect_stderr(stderr):
            status = ops.main(['--request-file', str(self.request), '--allowlist-file', str(self.allowlist), '--output-bundle', str(self.output)])
        self.assertEqual(status, 2)
        self.assertEqual(json.loads(stdout.getvalue())['status'], 'publication_unconfirmed')
        self.assertEqual(stderr.getvalue(), '')
        self.assertNotIn('synthetic-sensitive', stdout.getvalue())
        self.assertEqual(set(p.name for p in self.output.iterdir()), {'handoff.json', 'server-record.json'})
        with self.assertRaises(ops.InvitationError): self.generate()

    def test_cli_failure_never_echoes_input_or_exception(self):
        self.request.write_text('{"secret":"synthetic-do-not-print", invalid')
        result = subprocess.run(['python3', str(ROOT / 'tool/generate_staging_password_invitation.py'), '--request-file', str(self.request), '--allowlist-file', str(self.allowlist), '--output-bundle', str(self.output)], capture_output=True)
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual(result.stderr, b'')
        self.assertEqual(json.loads(result.stdout), {'status': 'denied'})
        result = subprocess.run(['python3', str(ROOT / 'tool/generate_staging_password_invitation.py'), '--email', 'synthetic-do-not-print'], capture_output=True)
        self.assertNotEqual(result.returncode, 0)
        self.assertNotIn(b'synthetic-do-not-print', result.stdout + result.stderr)


if __name__ == '__main__':
    unittest.main()
